Tutorial to start a new Telestion project
wuespace/telestion-docs pull request #110
Opened 2021-11-15 13:48 UTC by fussel178

### Summary 

Add a tutorial to start a new project.

### Details 

A first iteration on the steps required to set up a new Telestion project. :wink: 

### Additional information 

n/a

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2021-11-16 17:43 UTC, pklaschka requested changes
I have one major request (see below) and a few minor improvements which I've left as inline comment suggestions 🙂

### The major request
Tutorial titles should be written in present progressive ("-ing"-form), i.e., here, "Starting a new project" instead of "Start a new project". I've left inline suggestions to change it in the text, but you'll need to rename the file 🙂 

Other than that, it looks good to me 🙂

2021-11-16 17:43 UTC, pklaschka commented on docs/application/tutorials/start-a-new-project.mdx
> +That's it!
```suggestion
First, log into GitHub with your user account.

Head to our project template and press the `Use this template button`.

<Reference to="https://github.com/wuespace/telestion-project-template">
  Telestion Project Template
</Reference>

<Image src="/img/new-project/github-use-this-template.png" alt="GitHub's Use this template button" />

Now, GitHub asks you some required information.
Select a suitable user/group and give the repository a meaningful name.

Next, select your repository's visibility.
When you are satisfied with your information, press the `Create repository from template` button.

<Image src="/img/new-project/github-create-repo.png" alt="GitHub's Create repository from template interface" />

That's it!
```

2021-11-16 17:43 UTC, pklaschka commented on docs/application/tutorials/start-a-new-project.mdx
> +:::
```suggestion
Now, you should have a new repository under your control.

Next, initialize the Telestion project.
Our template already has a GitHub Action configuration that does the initialization steps for you.

Go to the `Actions` tab and select the `Initialize` in the left sidebar.

<Image src="/img/new-project/github-actions-initialize.png" alt="GitHub Actions page with the selected Initialize action" />

Now press the `Run workflow` button in the Action list.
In the popup, enter your preferences and then press `Run workflow`.

<Image src="/img/new-project/github-initialize-run-workflow.png" alt="Open popup to run the Initialize workflow in GitHub Actions" />

:::tip Java package naming

We recommend following the
[Maven Central `groupId` naming conventions](https://maven.apache.org/guides/mini/guide-naming-conventions.html), 
e.g., beginning with the company URL in reverse.

:::
```

2021-11-16 17:43 UTC, pklaschka commented on docs/application/tutorials/start-a-new-project.mdx
> +description: Start a new Telestion Project with the Telestion Project template
```suggestion
title: Starting a new Project
# e.g., "Publishing messages to the event bus" or "Installing a dependency using npm"

description: Start a new Telestion Project with the Telestion Project template
```

2021-11-16 17:43 UTC, pklaschka commented on docs/application/tutorials/index.mdx
> +	<Reference to="start-a-new-project">Start a new project</Reference>
```suggestion
	<Reference to="starting-a-new-project">Starting a new project</Reference>
```

2021-11-16 17:43 UTC, pklaschka commented on docs/application/tutorials/start-a-new-project.mdx
> +Next steps: Coming soon™
Looking forward to that 😁

2021-11-18 23:46 UTC, fussel178 commented on docs/application/tutorials/start-a-new-project.mdx
> +Next steps: Coming soon™
:wink:

2021-11-18 23:49 UTC, fussel178 commented
Done! :D

2021-11-18 23:50 UTC, pklaschka approved these changes

2021-11-18 23:50 UTC, merged

2021-11-18 23:51 UTC, pklaschka commented
@fussel178 Congrats on your first documentation article! 🍰