Write basic Application Development tutorials
wuespace/telestion-docs pull request #112
Opened 2021-11-16 23:34 UTC by pklaschka

### Summary 

Adds tutorials for the basics of Telestion Project development (writing Verticles, etc.)

### Details 

n/a

### Additional information 

n/a

### Related links 

n/a

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2021-11-19 00:34 UTC, pklaschka commented on docs/application/tutorials/202-adding-configuration-options.mdx
> +inconvenience function.
```suggestion
After that, all that you need to do is to add another parameter in the Telestion
convenience function.
```

2021-11-19 00:41 UTC, fussel178 requested changes
One little thing. Everything else is really nice. Thumbs up :+1:

2021-11-19 00:41 UTC, fussel178 commented on docs/application/tutorials/200-writing-a-verticle.mdx
> +simply logs all incoming messages to a file or saved them to the database. In
```suggestion
simply logs all incoming messages to a file or saves them to the database. In
```

2021-11-19 02:46 UTC, fussel178 submitted a review, later dismissed
LGTM! :palm_tree:

2021-11-21 12:03 UTC, cb0s reviewed
In general I really quite like this! There are some small hick-ups here and there which I marked for you to correct.

Apart from that I really have just one last question: We just developed a new system for the "best-practice"-structure. Wouldn't it maybe confuse people if we changed this in let's say one or two weeks with a breaking change?

2021-11-21 12:09 UTC, pklaschka commented on docs/application/tutorials/200-writing-a-verticle.mdx
> +			int received = (int) message.body(); // cast body to integer
It was, originally, intentional as in "hey, this is now an integer!", but I agree that since we explicitly cast it, we can drop that

2021-11-21 12:11 UTC, pklaschka commented on docs/application/tutorials/201-using-jsonmessage.mdx
> +							int received = message.value();
In this case, as it no longer gets explicitly casted, I'd like to keep it explicit to make it easier to digest when reading it (and more obvious what happens as it introduces the new concept).

2021-11-21 12:20 UTC, pklaschka commented on docs/application/tutorials/202-adding-configuration-options.mdx
> +	@SuppressWarnings("unused")
As per direct messages, this was marked in the wrong spot => resolving this

2021-11-21 12:20 UTC, pklaschka commented on docs/application/tutorials/202-adding-configuration-options.mdx
> +	@SuppressWarnings("unused")
As per direct messages, this was marked in the wrong spot => resolving this

2021-11-21 12:24 UTC, pklaschka commented
@cb0s :

> Apart from that I really have just one last question: We just developed a new system for the "best-practice"-structure. Wouldn't it maybe confuse people if we changed this in let's say one or two weeks with a breaking change?

The thing is that it'll be easier to update the documentation when changes come along.

Documentation should always describe the current state, not what it'll be in the future. Also, various parts of our projects will take time to adapt (if they even do so at all), meaning it's good to have documentation about how the structure worked in the past, as well.

Overall, I like the feedback and if this were a release of a software project, so to speak, I would agree that we should wait. Since, however, the "status quo" is already released and the documentation aims to document the latest released state to its fullest extent, I think it makes sense to release the docs for the previous version, as well. Then, we can adjust the docs as soon as the new structure gets released and explicitly mark a docs release with a changelog about "now covering the new way to write Verticles" 😉

2021-11-21 12:26 UTC, pklaschka commented on docs/application/tutorials/201-using-jsonmessage.mdx
> +function. This, then, filters messages and calls a handler passed into it if and
Grammatically, it would be correct to have the commas, but we can also change it (that's not a hill I want to die on 😜 )

2021-11-21 12:31 UTC, cb0s commented on docs/application/tutorials/201-using-jsonmessage.mdx
> +							int received = message.value();
Ok. I see your point. :)

2021-11-21 12:32 UTC, cb0s approved these changes
LGTM 💯

2021-11-21 12:39 UTC, merged