Web Client dialogs
wuespace/telestion-docs pull request #160
Opened 2022-01-27 17:05 UTC by fussel178

### Summary 

Adds tutorials how to add static and stateful dialogs to your web client.

### Details 

n/a

### Additional information 

n/a

### CLA

- [x] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2022-01-27 18:00 UTC, pklaschka requested changes
Overall, great tutorials. I've left a few comments here and there, but apart from these minor change requests, it looks awesome!

![Added via Giphy](https://media2.giphy.com/media/3o7qDON1FYhi5eoqgU/giphy.gif?cid=e1bb72ffijh5t0mcd414cdkh5h92qtfk60ex1vh9ct8nhfyn&rid=giphy.gif&ct=g)

2022-01-27 19:59 UTC, fussel178 commented on docs/client/tutorials/301-writing-a-stateful-dialog.mdx
> +and add delivery options to our telecommand we want to send.
Not here :package:

2022-01-27 22:43 UTC, fussel178 commented on docs/client/tutorials/301-writing-a-stateful-dialog.mdx
> +and add delivery options to our telecommand we want to send.
Done in [`a4df0f4` (#160)](https://github.com/wuespace/telestion-docs/pull/160/commits/a4df0f4657de47e4ebf85dbf3d3f655867cf0731)

2022-01-27 22:43 UTC, fussel178 commented on docs/client/tutorials/300-writing-a-static-dialog.mdx
> +or the `content` property the center part of the dialog.
Done in [`a4df0f4` (#160)](https://github.com/wuespace/telestion-docs/pull/160/commits/a4df0f4657de47e4ebf85dbf3d3f655867cf0731)

2022-01-27 22:43 UTC, fussel178 commented on docs/client/tutorials/300-writing-a-static-dialog.mdx
> +If you start the Web Client and add the widget to your dashboard you should see something like:
Done in [`a4df0f4` (#160)](https://github.com/wuespace/telestion-docs/pull/160/commits/a4df0f4657de47e4ebf85dbf3d3f655867cf0731)

2022-01-27 22:44 UTC, fussel178 commented on docs/client/tutorials/300-writing-a-static-dialog.mdx
> +In this tutorial, we write a static dialog for a widget in the web client.
Done in [`a4df0f4` (#160)](https://github.com/wuespace/telestion-docs/pull/160/commits/a4df0f4657de47e4ebf85dbf3d3f655867cf0731)

2022-01-28 12:22 UTC, pklaschka approved these changes
LGTM!!

[cool](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/cool.gif)

2022-01-29 19:07 UTC, pklaschka approved these changes

2022-01-29 19:10 UTC, merged